# This is a Nord+ theme
background=#1E222A
foreground=#D8DEE9
cursor=#D8DEE9

color0=#3B4252
color1=#FF6B6B
color2=#A3FFB5
color3=#FFD166
color4=#5DA9FF
color5=#C792EA
color6=#5FE3D3
color7=#E5E9F0

color8=#4C566A
color9=#FF8787
color10=#B9FFCB
color11=#FFE08A
color12=#82CFFF
color13=#D6A8FF
color14=#8CF8F0
color15=#ECEFF4
